[package]
name = "synchronous_gossip_protocol"
authors = ["Dinesh Pinto <annual.fallout_0z@icloud.com>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]