name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with cargo
        run: cargo build --verbose
      - name: Run cargo tests
        run: cargo test --verbose
      - name: Set up poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install Python dependencies
        run: poetry install
      - name: Build wheel with maturin
        run: poetry run maturin build
      - name: Install wheel
        run: poetry add target/wheels/*.whl
